version: '3.3'

services:
  nginx:
    image: nginx
    container_name: nginx
    labels:
      - sh.acme.autoload.domain=yottc.com

acme.sh:
  image: neilpang/acme.sh
  container_name: acme.sh
  command: daemon

  volumes:
    - ./acmeout:/acme.sh
    - /var/run/docker.sock:/var/run/docker.sock
    
  environment:
    - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=yottc.com
    - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/nginx/ssl/yottc.com/key.pem
    - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/nginx/ssl/yottc.com/cert.pem"
    - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/nginx/ssl/yottc.com/ca.pem"
    - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="etc/nginx/ssl/yottc.com/full.pem"
    - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload"
